/**
 * Risk Import Script
 * 
 * This script imports the 47 IT and cybersecurity risks from the Saudi Ceramics risk assessment
 * into the MetaWorks platform database.
 */

import { db } from '../server/db';
import { risks } from '../shared/schema';

const allRisks = [
  // 1-20: Original risks
  {
    title: "Absence of IT Strategy",
    description: "Unclear IT governance for business goals.",
    cause: "Lack of cybersecurity strategy.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Develop IT strategy and roadmap.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Periodic IT Policy Reviews",
    description: "Outdated policies lead to inefficiencies.",
    cause: "No review process.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Last reviewed in 2020.",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Regular policy updates.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Missing IT Steering Committee",
    description: "No oversight for IT operations.",
    cause: "No committee/charter.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Establish committee and charter.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Absence of Job Descriptions",
    description: "Unclear IT staff roles.",
    cause: "No documented JD.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "JDs exist",
    controlEffectiveness: "Effective",
    residualRiskLevel: "Medium",
    mitigationActions: "Create and maintain job descriptions.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Manual IT Asset Management",
    description: "Errors in asset tracking.",
    cause: "No centralized tool.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Implement asset management tool.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No IT Asset Classification",
    description: "Can't prioritize critical assets.",
    cause: "No classification process.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Classify all assets.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "EOL/EOS Assets in Use",
    description: "Vulnerable outdated systems.",
    cause: "No EOL tracking.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Maintain EOL records.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No IT Asset Disposal Records",
    description: "Risk of data breaches.",
    cause: "No disposal docs.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Medium",
    inherentRiskLevel: "Medium",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "Medium",
    mitigationActions: "Document disposals.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Technical Evaluation for IT Purchases",
    description: "Compatibility issues.",
    cause: "No evaluation process.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Medium",
    inherentRiskLevel: "Medium",
    existingControls: "Evaluations done",
    controlEffectiveness: "Effective",
    residualRiskLevel: "Low",
    mitigationActions: "Implement formal technical evaluation.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Manual Change Management",
    description: "Approval delays/errors.",
    cause: "No automation.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Manual process",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement change management tool.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No DR Plan or BCP",
    description: "Extended outages possible.",
    cause: "No DR planning.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Catastrophic",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Create and test DR/BCP.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Missing Backup Strategy",
    description: "Data loss risk.",
    cause: "No formal backup plan.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Catastrophic",
    inherentRiskLevel: "High",
    existingControls: "Ad-hoc backups",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement comprehensive backup strategy.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Smoke/Fire Detection in Server Room",
    description: "Physical damage risk.",
    cause: "No detection systems.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Unlikely",
    impact: "Catastrophic",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None", 
    residualRiskLevel: "High",
    mitigationActions: "Install detection systems.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Data Classification",
    description: "Improper data handling.",
    cause: "No classification scheme.",
    category: "Compliance",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Implement data classification.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Missing SLAs for Third Parties",
    description: "Unmanaged vendor performance.",
    cause: "No SLA requirements.",
    category: "Compliance",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Medium",
    inherentRiskLevel: "Medium",
    existingControls: "Some SLAs exist",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement SLAs for all vendors.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No SIEM Solution",
    description: "Can't correlate security events.",
    cause: "No SIEM deployed.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Deploy SIEM.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Cybersecurity Team",
    description: "Inconsistent security measures.",
    cause: "No dedicated team.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Establish cybersecurity function.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Security Training",
    description: "Employees vulnerable to phishing.",
    cause: "No awareness program.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Conduct regular security training.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Privileged Access Management",
    description: "Abuse of privileges possible.",
    cause: "No PAM solution.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Manual controls",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement PAM solution.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Weak Password Policy",
    description: "Easily guessed passwords.",
    cause: "Insufficient password requirements.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic policy exists",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Strengthen password policy.",
    isAccepted: false,
    companyId: 1
  },
  
  // 21-47: Additional risks from the Saudi Ceramics assessment
  {
    title: "No MFA for Critical Systems",
    description: "Increased risk of unauthorized access.",
    cause: "MFA not implemented for key systems.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "MFA on some systems",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement MFA for all critical systems.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Missing Vulnerability Management",
    description: "Undetected system vulnerabilities.",
    cause: "No regular vulnerability scanning.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Ad-hoc scanning",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement vulnerability management program.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Network Segmentation",
    description: "Lateral movement possible for attackers.",
    cause: "Flat network architecture.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic firewalls",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement network segmentation.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Inadequate Log Monitoring",
    description: "Delayed detection of suspicious activities.",
    cause: "No centralized logging solution.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic logging",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement centralized log management.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Encryption for Data in Transit",
    description: "Data interception risk.",
    cause: "Missing TLS/SSL implementation.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Partial encryption",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement encryption for all data in transit.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Missing Access Review Process",
    description: "Accumulated privileges over time.",
    cause: "No regular access reviews.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Ad-hoc reviews",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement quarterly access reviews.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Web Application Firewall",
    description: "Web applications vulnerable to attacks.",
    cause: "No WAF deployed.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Deploy WAF for all web applications.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Outdated Antivirus Solution",
    description: "Reduced protection against malware.",
    cause: "Legacy AV solution.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Basic AV installed",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Upgrade to EDR solution.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Data Loss Prevention (DLP)",
    description: "Potential data exfiltration.",
    cause: "No DLP controls.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Implement DLP solution.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Formalized Incident Response Plan",
    description: "Delayed incident response.",
    cause: "No documented IR procedures.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Ad-hoc response",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Develop and test incident response plan.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Incomplete Software Inventory",
    description: "Shadow IT risk.",
    cause: "No software asset management.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Partial inventory",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement software asset management.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Third-Party Risk Management",
    description: "Supply chain security risks.",
    cause: "No vendor assessment process.",
    category: "Compliance",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic contracting",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement third-party risk management program.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Insufficient Remote Access Security",
    description: "Unauthorized remote access risk.",
    cause: "Weak remote access controls.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic VPN",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Enhance remote access security controls.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Secure Development Practices",
    description: "Security vulnerabilities in code.",
    cause: "No secure SDLC.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Implement secure development lifecycle.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Data Backup Encryption",
    description: "Backup data theft risk.",
    cause: "Unencrypted backups.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Implement backup encryption.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Inadequate Mobile Device Management",
    description: "Corporate data on unsecured devices.",
    cause: "No MDM solution.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Basic policies",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement MDM solution.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Lack of Security Monitoring",
    description: "Delayed threat detection.",
    cause: "No 24/7 monitoring.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Partial monitoring",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement 24/7 security monitoring.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No System Hardening Standards",
    description: "Default configurations in use.",
    cause: "No hardening baselines.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Basic hardening",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Develop and implement hardening standards.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Email Security Gateway",
    description: "Phishing/malware risk via email.",
    cause: "Basic email filtering only.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic spam filtering",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement advanced email security gateway.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Regular Security Assessments",
    description: "Unknown security posture.",
    cause: "No scheduled assessments.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Ad-hoc assessments",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement regular security assessments.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Insufficient Physical Security",
    description: "Unauthorized physical access risk.",
    cause: "Inadequate physical controls.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Possible",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Basic access controls",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Enhance physical security controls.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Penetration Testing",
    description: "Unidentified security weaknesses.",
    cause: "No regular penetration tests.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "High",
    mitigationActions: "Conduct regular penetration testing.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Incomplete User Offboarding Process",
    description: "Former employee access risk.",
    cause: "No formal offboarding checklist.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Partial process",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement comprehensive offboarding process.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Lack of Patch Automation",
    description: "Delayed security patches.",
    cause: "Manual patching process.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Very Likely",
    impact: "Major",
    inherentRiskLevel: "High",
    existingControls: "Manual patching",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "High",
    mitigationActions: "Implement automated patch management.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "Insecure File Sharing",
    description: "Data exposure through sharing.",
    cause: "No secure file sharing solution.",
    category: "Operational",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Serious",
    inherentRiskLevel: "High",
    existingControls: "Basic controls",
    controlEffectiveness: "Needs Improvement",
    residualRiskLevel: "Medium",
    mitigationActions: "Implement secure file sharing platform.",
    isAccepted: false,
    companyId: 1
  },
  {
    title: "No Security Metrics",
    description: "Unable to measure security posture.",
    cause: "No defined security metrics.",
    category: "Strategic",
    owner: "IT Department",
    likelihood: "Likely",
    impact: "Medium",
    inherentRiskLevel: "Medium",
    existingControls: "None",
    controlEffectiveness: "None",
    residualRiskLevel: "Medium",
    mitigationActions: "Develop and implement security metrics program.",
    isAccepted: false,
    companyId: 1
  }
];

async function importRisks() {
  console.log("Starting risk import...");
  
  try {
    if (!db) {
      throw new Error("Database connection is not available");
    }
    
    // Import each risk
    for (const risk of allRisks) {
      await db.insert(risks).values({
        ...risk,
        createdAt: new Date(),
        updatedAt: new Date()
      });
    }
    
    console.log(`Successfully imported ${allRisks.length} risks!`);
  } catch (error) {
    console.error("Error importing risks:", error);
  }
}

// Run the import function
importRisks()
  .then(() => {
    console.log("Import complete!");
    process.exit(0);
  })
  .catch(err => {
    console.error("Import failed:", err);
    process.exit(1);
  });